### ISSUE TITLE
how to get download of uploaded file

### ISSUE THREAD

**Issue by sagar3506** [Ideneal/OpenLoad#3]
Hello sir Your Api is working great for me but i stuck at get download link uploaded file sorry for my bad english

**Comment by Ideneal** [comment]
In order to get a download link of an uploaded resource you must have the ticket first.
The ticket shows you the captcha info. You have to retrieve the captcha from the tiket, go to the captcha url and see the captcha code.
After that you have to pass the captcha code and ticket to the getDownloadLink method.

**Comment by sagar3506** [comment]
thanks bro

i get it without any ticket


[image: Inline image 1]

**Comment by sagar3506** [comment]
thanks bro 

i get it without any ticket 
<img src="https://gm1.ggpht.com/DpCIB6D_kIFfBK4pGFBNT1fCgDvavD78Iy5sTuC_AJKVs_uhob0TlpsHr2M_ySq0kbmPnvM7i_GBqS2rqTPZon_MD_YP73PRr4L1OOxpW06L-GwS6EWT32cJ_tqsSgnr7K_h-hE6-Wo_JtJe-QxhOot4l7Nj_piYp4hys1uKDZHzp_wYn6Ch-MbeSoyGiYzgZIX1fSeKudE0b1Se_TvJRdBSTnR3nJ1HMAOkXIuQdBZpAJGcbSCY9uwreVvhkXwdrNcMapjVnoxkD4DWc_Zhxv-_5o-YGFfLXO-g0A165xZhDO-irhCtggoXApXGqwQdrXepxrVxVgFIYnPnlmNyCxpJ51XTbp1oI2CPZjdAQEBgN6GWoYiraLFQIhImszfOrFX98YLUI71dY7QIk7T1mqwwxSvwsk2pYprlXZRTMFMMulw8qCaTNpSZAqKH8pyWyE0sziXrvLXmdSgr-tPSsg8kBahHhf-pmcbY75pA3KK0ki1w0_Kx29_k3_0E35jcWf1HzdBy0LHNnH1NijgnpU335htj47Tc-mieAG2cXaT-VR7CZNZaiewrckuSwgRh2E-pdmC7DLHC_sBqco9kjebJdEyTttKqcUxk8YLMzG8b4HCJqyP3UsJbhkG8xYTkqXN2pDyU9CrJAQEl5IyeycAysFta9nNHYpEbYoescTRIsS7SsOLtElodhP7jUZ63RQVYZ67r96G4LA=w1366-h638-l75-ft"></img>
